apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: image-puller-operator-subscription
  namespace: default
spec:
  channel: stable
  name: kubernetes-imagepuller-operator
  startingCSV: kubernetes-imagepuller-operator.v0.0.3
  source: kubernetes-image-puller-operator-preview-catalog
  sourceNamespace: olm
